language: java

env:
  DOCKER_COMPOSE_VERSION: 1.23.2

services:
  - docker

before_install:
  - docker-compose --version
  - docker-compose build
  - docker-compose start
  - docker ps
  - docker/web/provision.sh
  
#install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

#jdk:
 # - oraclejdk8

#after_success:
  # - mvn clean test jacoco:report coveralls:report
