version: '3.1'

services:

    gateway: 
        build: ./gateway/   
        depends_on:
          - registry
        ports:
            - '8080:8080'
        restart: on-failure
      
    registry: 
        build: ./discovery/
        ports:
            - '8761:8761'
      
#    mongodb:
#        image: mongo:latest
#        environment:
#            - MONGO_INITDB_DATABASE=dicom
#        ports:
#            - '27017:27017'

    medicinedb:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
        # Where our data will be persisted
        volumes:
            - dicom-db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: 'dicom'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'admin'
            # You can use whatever password you like
            MYSQL_PASSWORD: '4dm1n'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'd1c0m'
#        environment:
#            - MYSQL_ROOT_PASSWORD=d1c0m
#            - MYSQL_DATABASE=dicom
#            - MYSQL_USER=admin
#            - MYSQL_PASSWORD=4dm1n

    dicom:
        build: ./dicom/
        container_name: dicom_container
        ports:
            - '8086:8086'
        depends_on:
            - medicinedb
            - registry
            - gateway
        restart: on-failure

# Names our volume
volumes:
    dicom-db: